![image-20210629132710523](E:\web\vue\笔记\image-20210629132710523.png)

![image-20210629132750760](E:\web\vue\笔记\image-20210629132750760.png)

![image-20210629132820471](E:\web\vue\笔记\image-20210629132820471.png)



![image-20210629132919072](E:\web\vue\笔记\image-20210629132919072-1624944559638.png)







![image-20210629133152947](E:\web\vue\笔记\image-20210629133152947.png)

 ## axios 全局配置



![image-20210629142314140](E:\web\vue\笔记\image-20210629142314140.png)





````
import Vue from 'vue'
import App from './App.vue'
import router from './router'
import store from './store'
import axios from 'axios'

Vue.config.productionTip = false
// 全局配置
axios.defaults.baseURL = 'http://123.207.32.32:8000'
axios.defaults.timeout = 5000
new Vue({
  router,
  store,
  render: h => h(App)
}).$mount('#app')
axios({
  url:'/home/multidata',
  method:'get'
}).then(res=>{
 console.log(res)
})
axios.all([
  axios({
    url:'/home/multidata'
  }),
  axios({
    url:'http://123.207.32.32:8000/home/data',
    params:{
      type:'sell',
      page:4
    }
  })
]).then(axios.spread((res1,res2)=>{
  console.log(res1)
  console.log(res2)

}))
````

## axios 封装

写法一  传入三个参数

```
import axios from 'axios'
export function request(config,success,failure){
  const instance = axios.create({
    baseURL:'http://123.207.32.32:8000',
    timeout:5000
  })
  instance(config)
  .then(res=>{
    // 成功执行这个回调
    success(res)
  })
  .catch(err=>{
    // 失败执行这个回调
    failure(err)
  })
}
```

其他函数里面调用 

```
import {request} from './network/request'
// 这个函数需要三个参数 第一个是url 第二个成功回调函数 。第三个失败回调函数
request({
  url:'/home/multidata'
},
  res=>{
    console.log(res)
  },err=>{
    console.log(err)
  }
)
```

写法二 ：传入一个对象

```
export function request(config){
  const instance = axios.create({
    baseURL:'http://123.207.32.32:8000',
    timeout:5000
  })
  instance(config.baseconfig)
  .then(res=>{
    // 成功执行对象里面这个方法
    config.success(res)
  })
  .catch(err=>{
    // 失败执行这个对象里面这个方法
    config.failure(err)
  })
}
```



调用

```
import {request} from './network/request'
request({
  baseconfig:{
    url:'/home/multidata',
  },
  success(res){
    console.log(res)
  },
  failure(err){
    console.log(err)
  }
})
```



第三种:采用promise

```
export function request(config){
  // 异步操作 直接返回成功 或者失败的
  return new Promise((resolve,reject)=>{
    const instance = axios.create({
      baseURL:'http://123.207.32.32:8000',
      timeout:5000
    })
    instance(config)
    .then(res=>{
      // 成功执行对象里面这个方法
      resolve(res)
    })
    .catch(err=>{
      // 失败执行这个对象里面这个方法
      reject(err)
    })
  

  })
}
```

```
request({
  url:'/home/multidata',
}).then(res=>{
  console.log(res)
}).catch(err=>{
  console.log(err)
})
```

第四种直接return

```
export function request(config){
  // 异步操作 直接返回成功 或者失败的
  
    const instance = axios.create({
      baseURL:'http://123.207.32.32:8000',
      timeout:5000
    })
    // 返回值本身就是一个promise
    return instance(config)
}
```

```
request({
  url:'/home/multidata',
}).then(res=>{
  console.log(res)
}).catch(err=>{
  console.log(err)
})
```

## 拦截器

![image-20210629172515011](E:\web\vue\笔记\image-20210629172515011.png)

```
export function request(config){
  // 异步操作 直接返回成功 或者失败的
  
    const instance = axios.create({
      baseURL:'http://123.207.32.32:8000',
      timeout:5000
    })
    // 请求拦截器 ，成功 或失败
    instance.interceptors.request.use(config=>{
      // 拦截后必须返回
      // 
      console.log(config)
      return config
    },err=>{
      console.log(err)
    })
    // 
    // 响应拦截
    instance.interceptors.response.use(config =>{
      console.log(config)
      return config.data.data
    },err=>{
      console.log(err)
    })
    return instance(config)
}
```

